import {responsiveHeight} from 'react-native-responsive-dimensions';
const {width, height} = Dimensions.get('window');

export const styles = StyleSheet.create({
    container: {
      flex: 1,
      flexDirection: 'column',
    },
    main: {
      flex: 1,
      backgroundColor: colors.lightBlue,
      borderRightWidth: 3,
      borderLeftWidth: 2,
      borderBottomWidth: 5,
      borderColor: colors.gray,
      marginHorizontal: 30,
      justifyContent: 'center',
      borderRadius: 60,
      alignItems:'center',
      alignContent:'center'
    },
    cardstack: {
      flex: 1,
      alignItems: 'center',
      justifyContent: 'center',
      // bottom: 10
      // marginVertical : 10,
    },
    card: {
      width: width,
      height: responsiveHeight(63),
    },
    mask: {
      width: '100%',
    },
    circle: {
      backgroundColor: colors.green,
      width: 48,
      height: 48,
      borderRadius: 24,
      justifyContent: 'center',
      alignItems: 'center',
      marginHorizontal: 8,
    },
    img: {
      flex: 1.5,
      width: '100%',
      // height: 300,
      borderRadius: 50,
    },
    back_img: {
      width: width / 4.5,
      height: 60,
      top: 10,
      left: 10,
      borderRadius: 20,
    },
    groupImg: {
      position: 'absolute',
      right: -6,
      top: -6,
      width: 40,
      height: 40,
    },
    m_avatar: {
      flex: 0.2,
      textAlign: 'center',
      padding: 10,
    },
    text: {
      color: colors.white,
      fontSize: RFValue(12, 580),
      fontFamily: 'ProximaNova-Bold',
    },
    text1: {
      color: colors.white,
      fontSize: 30,
      fontFamily: 'ProximaNova-Bold',
      fontWeight: '700',
      left: 20,
      top: 15,
    },
    text2: {
      flex: 1,
      color: colors.white,
      fontSize: 15,
      top: 20,
      marginHorizontal: 10,
      fontFamily: 'ProximaNova-Bold',
      fontWeight: '700',
    },
    text6: {
      color: colors.white,
      fontSize: 20,
      fontFamily: 'ProximaNova-Bold',
      fontWeight: '700',
    },
    text7: {
      color: colors.white,
      fontSize: 10,
      fontFamily: 'ProximaNova-Bold',
      fontWeight: '700',
      textAlign: 'center',
    },
    title: {
      color: colors.white,
      fontSize: RFValue(23, 580),
      fontFamily: 'ProximaNova-Bold',
      fontWeight: '700',
    },
    bar: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
    },
    racket: {
      width: 50,
      height: 50,
      marginHorizontal: 10,
    },
    modalContainer: {
      flex: 1,
      width: '100%',
      alignItems: 'center',
      justifyContent: 'flex-end',
    },
    modal: {
      width: '100%',
      height: '100%',
      justifyContent: 'center',
      backgroundColor: 'rgba(0, 0, 0, 0.4)',
      position: 'absolute',
      bottom: 0,
      paddingBottom: 15,
      alignItems: 'center',
      paddingHorizontal: 20,
      // opacity: 0.2
    },
    absolute: {
      position: 'absolute',
      top: 0,
      left: 0,
      bottom: 0,
      right: 0,
    },
    btn: {
      backgroundColor: '#2ecc71',
      height: 50,
      width: '90%',
      borderRadius: 12,
      justifyContent: 'center',
      alignItems: 'center',
      marginTop: 16,
    },
    dot: {
      width: 18,
      height: 18,
      borderRadius: 9,
      marginTop: 8,
      backgroundColor: 'white',
    },
    text4: {
      color: 'white',
      marginTop: 6,
      fontSize: 30,
      fontFamily: 'ProximaNova-Regular',
      textAlign: 'center',
      fontWeight: '700',
    },
    text5: {
      color: 'white',
      marginTop: 12,
      fontSize: 18,
      fontFamily: 'ProximaNova-Regular',
      textAlign: 'center',
      fontWeight: '700',
    },
    item: {
      marginTop: 8,
      flexDirection: 'row',
      alignItems: 'center', 
    },
    btn_date: {
      // width: 100,
      // height: 40,
      // backgroundColor: '#34495E',
      // borderRadius: 8,
      // justifyContent: 'center',
      // alignItems: 'center',
      // marginRight: 40,
      // marginLeft: 10,
      width: '35%',
      height: 45,
      backgroundColor: '#34495E',
      borderRadius: 8,
      justifyContent: 'center',
      alignItems: 'center',
      marginRight: 40,
    },
    text3: {
      color: '#fff',
      fontSize: 16,
      fontFamily: 'ProximaNova-Regular',
      fontWeight: '700',
    },
    circle_date: {
      backgroundColor: colors.green,
      width: 35,
      height: 35,
      borderRadius: 21,
      justifyContent: 'center',
      alignItems: 'center',
      marginHorizontal: 5,
      marginVertical: 1,
    },
    text_date: {
      color: '#fff',
      fontSize: 12,
      fontFamily: 'ProximaNova-Regular',
    },
    oval: {
      width,
      height: width / 2,
      position: 'absolute',
      bottom: -width / 4,
    },
    footer: {
      flexDirection: 'row',
      justifyContent: 'center',
    },
    icon: {
      marginHorizontal: 12,
      marginBottom: responsiveHeight(2),
      width: responsiveHeight(9),
      height: responsiveHeight(9),
    },
  });
  